-- CreateEnum
ALTER TYPE "PostType" ADD VALUE 'DAILY_DRAW_REFLECTION';
ALTER TYPE "PostType" ADD VALUE 'SPREAD_BREAKDOWN';
ALTER TYPE "PostType" ADD VALUE 'CARD_STUDY';
ALTER TYPE "PostType" ADD VALUE 'INTUITIVE_MESSAGE';
ALTER TYPE "PostType" ADD VALUE 'TAROT_LIFE_EVENT';
ALTER TYPE "PostType" ADD VALUE 'DECK_REVIEW_COMPARISON';
ALTER TYPE "PostType" ADD VALUE 'THEME_BASED_READING';
ALTER TYPE "PostType" ADD VALUE 'TAROT_PROMPT_RESPONSE';
ALTER TYPE "PostType" ADD VALUE 'SYMBOL_ARCHETYPE_EXPLORATION';
ALTER TYPE "PostType" ADD VALUE 'MONTHLY_RECAP';